# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     invalid_use_of_protected_member: false

analyzer:
  exclude:
    - lib/src/i18n/messages_hr.dart
    - lib/src/i18n/messages_en.dart